version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.myhome.de'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.myhome.de'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server-cert.pem"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server-key.pem"
#        nginx['ssl_dhparam'] = "/etc/gitlab/ssl/dhparams.pem"
    ports:
      - '443:443'
      - '80:80'
      - '2222:2222'
    shm_size: '256m'
    volumes:
      - ./volume_data/conf:/etc/gitlab
      - ./volume_data/ssl:/etc/ssl/certs/gitlab
      - ./volume_data/logs:/var/log/gitlab
      - ./volume_data/main:/var/opt/gitlab