version: "3.9"
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - traefik

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://pass.duckdns.org
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
#    ports:
#      - 80:80
#      - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pass.rule=Host(`pass.duckdns.org`)"
      - "traefik.http.routers.pass.entrypoints=websecure"
      - "traefik.http.services.pass.loadbalancer.server.port=80"
      - "traefik.http.routers.pass.service=pass"
      - "traefik.http.routers.pass.tls.certresolver=myresolver"
volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
networks:
  traefik:
    external:
      true