version: "3.7"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    hostname: vault
#    ports:
#      - 8200:8200
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - vault-volumes:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.duckdns.org`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
      - "traefik.http.routers.vault.service=vault"
      - "traefik.http.routers.vault.tls.certresolver=myresolver"
    networks:
      - traefik

  vault-init:
    image: hashicorp/vault:latest
    container_name: vault-init
    environment:
      - VAULT_ADDR=http://vault:8200
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
    volumes:
      - ./vault-root-token:/vault/file/vault-root-token
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - vault-volumes:/vault/file/
    command: /usr/local/bin/vault-init.sh
    restart: on-failure
    depends_on:
      - vault
    networks:
      - traefik

volumes:
  vault-volumes:
  
networks:
  traefik:
    external:
      true